'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Plant

    '''<summary>
    '''ButtonLuzSala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzSala As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzSala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzSala As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCozinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCozinha As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCozinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCozinha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCorredor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCorredor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCorredor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCorredor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzQuarto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzQuarto1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzQuarto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzQuarto1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzQuarto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzQuarto2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzQuarto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzQuarto2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzQuarto3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzQuarto3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzQuarto3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzQuarto3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCasaDeBanho1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCasaDeBanho1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCasaDeBanho1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCasaDeBanho1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCasaDeBanho2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCasaDeBanho2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCasaDeBanho2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCasaDeBanho2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageButtonLuzCasaDeBanho1On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCasaDeBanho1On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCasaDeBanho1Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCasaDeBanho1Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto1On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto1On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto1Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto1Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImagePlanta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagePlanta As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImageButtonLuzQuarto2On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto2On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto2Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto2Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCozinhaOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCozinhaOn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCozinhaOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCozinhaOff As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto3On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto3On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto3Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto3Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonCasaDeBanho2On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonCasaDeBanho2On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCasaDeBanho2Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCasaDeBanho2Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCorredorOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCorredorOn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCorredorOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCorredorOff As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzSalaOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzSalaOn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzSalaOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzSalaOff As Global.System.Web.UI.WebControls.ImageButton
End Class
