'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Plant

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''TimerRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TimerRefresh As Global.System.Web.UI.Timer

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ButtonLuzSala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzSala As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzSala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzSala As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCozinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCozinha As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCozinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCozinha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCorredor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCorredor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCorredor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCorredor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzQuarto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzQuarto1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzQuarto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzQuarto1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzQuarto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzQuarto2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzQuarto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzQuarto2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzQuarto3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzQuarto3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzQuarto3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzQuarto3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCasaDeBanho1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCasaDeBanho1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCasaDeBanho1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCasaDeBanho1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonLuzCasaDeBanho2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLuzCasaDeBanho2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelLuzCasaDeBanho2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzCasaDeBanho2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageButtonLuzCasaDeBanho1On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCasaDeBanho1On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCasaDeBanho1Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCasaDeBanho1Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto1On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto1On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto1Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto1Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImagePlanta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagePlanta As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImageButtonLuzQuarto2On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto2On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto2Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto2Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCozinhaOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCozinhaOn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCozinhaOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCozinhaOff As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto3On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto3On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzQuarto3Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzQuarto3Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonCasaDeBanho2On control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonCasaDeBanho2On As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCasaDeBanho2Off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCasaDeBanho2Off As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCorredorOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCorredorOn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzCorredorOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzCorredorOff As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzSalaOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzSalaOn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonLuzSalaOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonLuzSalaOff As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LabelAgendamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAgendamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelEscolherHoras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEscolherHoras As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListHH As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownListMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListMM As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownListSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListSS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LabelHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelHH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelLuzesSalaAgend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesSalaAgend As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxSalaOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSalaOn As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxSalaOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSalaOff As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesCorredorAgen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesCorredorAgen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxCorredorON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCorredorON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxCorredorOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCorredorOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesCozinhaAgen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesCozinhaAgen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxluzesCozinhaAgenON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesCozinhaAgenON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxluzesCozinhaAgenOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesCozinhaAgenOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesQuarto1Agen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesQuarto1Agen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxluzesQuarto1AgenON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesQuarto1AgenON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxluzesQuarto1AgenOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesQuarto1AgenOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesQuarto2Agen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesQuarto2Agen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxluzesQuarto2AgenON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesQuarto2AgenON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxluzesQuarto2AgenOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesQuarto2AgenOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesQuarto3Agen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesQuarto3Agen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxluzesQuarto3AgenON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesQuarto3AgenON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxluzesQuarto3AgenOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxluzesQuarto3AgenOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesCasaDeBanho1Agen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesCasaDeBanho1Agen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxLuzesCasaDeBanho1AgendON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxLuzesCasaDeBanho1AgendON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxLuzesCasaDeBanho1AgendOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxLuzesCasaDeBanho1AgendOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelLuzesCasaDeBanho2Agen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLuzesCasaDeBanho2Agen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxLuzesCasaDeBanho2AgendON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxLuzesCasaDeBanho2AgendON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxLuzesCasaDeBanho2AgendOFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxLuzesCasaDeBanho2AgendOFF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelEscolherData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEscolherData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelAno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelAnoRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAnoRes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelMesRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMesRes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelDia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListDias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListDias As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonFazerAgendamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonFazerAgendamento As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewAgendIndividual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAgendIndividual As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PanelAutorizacaoAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAutorizacaoAdmin As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LabelUserAutorizacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserAutorizacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelSalaAutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSalaAutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCorredorAutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCorredorAutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCozinhaAutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCozinhaAutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelQuarto1Autor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelQuarto1Autor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelQuarto2Autor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelQuarto2Autor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelQuarto3Autor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelQuarto3Autor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCasaDeBanho1Autor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCasaDeBanho1Autor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCasaDeBanhoAutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCasaDeBanhoAutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelAdminAutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAdminAutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelUsersEscolhidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUsersEscolhidos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxSalaAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSalaAutori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxCorredorAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCorredorAutori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxCozinhaAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCozinhaAutori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxQuarto1Autori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxQuarto1Autori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxQuarto2Autori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxQuarto2Autori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxQuarto3Autori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxQuarto3Autori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxCasaDeBanho1Autori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCasaDeBanho1Autori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxCasaDeBanho2Autori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCasaDeBanho2Autori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxAdminAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxAdminAutori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DropDownListUsersAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListUsersAutori As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonRefreshAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRefreshAutori As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonGravarAutori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonGravarAutori As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PlaceHolderTableAutorizaçoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderTableAutorizaçoes As Global.System.Web.UI.WebControls.PlaceHolder
End Class
